# ComfyUI Image Sync Configuration
# Updated by Enashka

# Google Drive folder ID where images will be uploaded
folder_id: "YOUR_FOLDER_ID"

# Sync interval in seconds
sync_interval: 5

# ComfyUI output directory
output_directory: "/workspace/ComfyUI/output"

# File extensions to sync
file_extensions:
  - ".png"
  - ".jpg"
  - ".jpeg" 